# Generated by Django 5.1.3 on 2024-11-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('NEBULOUS', 'Nebulous'), ('STARS', 'Stars'), ('GALAXIES', 'Galaxies'), ('PLANETS', 'Planets'), ('COMETS', 'Comets'), ('METEORS', 'Meteors'), ('ASTEROIDS', 'Asteroids'), ('OTHERS', 'Others')], default='OTHERS', max_length=100),
        ),
    ]
